name: Devcontainer build for ESP32-IDF targets # NOTE: we currently build against "All", since there is no optimized container.

on: # ESP32-IDF specific changes. We specifically ignore other (RTOS) target changes.
  push:
    paths:
      - '!**/*.md'
      - '.github/workflows/build-esp32-targets.yml'
      - '.devcontainer/sources/Dockerfile.ESP32'
      - '.devcontainer/Dockerfile.ESP32'
      - '.devcontainer/devcontainer.json'
      - 'targets/ESP32/**'
      - 'targets-community/ESP32/**'
      - 'src/**'
      - 'CMake/**'
      - 'bootloader_components/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  pull_request:
    paths:
      - '!**/*.md'
      - '.github/workflows/build-esp32-targets.yml'
      - '.devcontainer/sources/Dockerfile.ESP32'
      - '.devcontainer/Dockerfile.ESP32'
      - '.devcontainer/devcontainer.json'
      - 'targets/ESP32/**'
      - 'targets-community/ESP32/**'
      - 'src/**'
      - 'CMake/**'
      - 'bootloader_components/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  build-target:
    strategy:
      fail-fast: false # Continues to build other targets in the matrix, even if one fails.

      matrix: # Add the target and build type you wish to generate firmware for:
        include: [
          # { target: ESP32_REV0, build-type: MinSizeRel },
          # { target: ESP32_REV0, build-type: Debug },

          # { target: ESP32_PSRAM_REV3, build-type: MinSizeRel },
          # { target: ESP32_PSRAM_REV3, build-type: Debug },

          # { target: ESP32_PSRAM_XTAL26_REV0, build-type: MinSizeRel },
          # { target: ESP32_PSRAM_XTAL26_REV0, build-type: Debug },

          # { target: ESP32_REV3, build-type: MinSizeRel },
          # { target: ESP32_REV3, build-type: Debug },

          # { target: ESP32_PICO, build-type: MinSizeRel },
          # { target: ESP32_PICO, build-type: Debug },

          # { target: KALUGA_1, build-type: MinSizeRel },
          # { target: KALUGA_1, build-type: Debug },

          # { target: ESP32_BLE_REV3, build-type: MinSizeRel },
          # { target: ESP32_BLE_REV3, build-type: Debug },
          
          # { target: ESP32_OLIMEX, build-type: MinSizeRel },
          # { target: ESP32_OLIMEX, build-type: Debug },

          # { target: M5StickC, build-type: MinSizeRel },
          # { target: M5StickC, build-type: Debug },

          # { target: M5StickCPlus, build-type: MinSizeRel },
          # { target: M5StickCPlus, build-type: Debug },

          # { target: M5Core, build-type: MinSizeRel },
          # { target: M5Core, build-type: Debug },

          { target: M5Core2, build-type: MinSizeRel },
          { target: M5Core2, build-type: Debug },

          # { target: AtomS3, build-type: MinSizeRel },
          # { target: AtomS3, build-type: Debug },

          # { target: ESP32_C3_REV3, build-type: MinSizeRel },
          # { target: ESP32_C3_REV3, build-type: Debug },

          # { target: ESP32_GenericDisplay_REV0, build-type: MinSizeRel },
          # { target: ESP32_GenericDisplay_REV0, build-type: Debug },

          # { target: ESP32_PSRAM_BLE_GenericGraphic_REV3, build-type: MinSizeRel },
          # { target: ESP32_PSRAM_BLE_GenericGraphic_REV3, build-type: Debug },

          # { target: XIAO_ESP32C3, build-type: MinSizeRel },
          # { target: XIAO_ESP32C3, build-type: Debug },

          # { target: ESP32_S3_BLE, build-type: MinSizeRel },
          # { target: ESP32_S3_BLE, build-type: Debug },


          # Community targets:

        ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update repo submodules
        run: |
          git submodule update --init

      - name: Adjust config templates for devcontainer
        run: |
            # Move into the config directory
            pushd config
            
            # Rename the templates
            mv user-prefs.TEMPLATE.json user-prefs.json
            mv user-tools-repos.TEMPLATE.json user-tools-repos.json
           
            # Adjust the file content for a devcontainer
            sed -i -- 's|"name": "user-tools-repos-container"|"name": "user-tools-repos"|g' user-tools-repos.json
            
            # Move out of the config directory
            popd

      - name: Adjust devcontainer.json (ESP32-IDF)
        run: |
            # Move into the .devcontainer directory
            pushd .devcontainer

            # target the ESP32 container for a quicker build
            # sed -i -- 's|"dockerFile": "Dockerfile.All"|"dockerFile": "Dockerfile.ESP32"|g' devcontainer.json

            # But if needed, we could change to the available devcontainer image, so we target the source instead (which takes a little longer to build).
            sed -i -- 's|"dockerFile": "Dockerfile.All"|"dockerFile": "sources/Dockerfile.ESP32"|g' devcontainer.json

            # Move out of the .devcontainer directory
            popd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target }} ${{ matrix.build-type }} Firmware
        uses: devcontainers/ci@v0.3
        with:
          # The ESP32 container
          # cacheFrom: ghcr.io/nanoframework/dev-container-esp32
          push: never
          runCmd: |
            # Build target:
            cmake --preset=${{ matrix.target }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
            cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firmware ${{ matrix.target }}-${{ matrix.build-type }}
          path: |
            ./build/*.map
            ./build/*.elf
            ./build/*.hex
            ./build/*.bin
            ./build/*.dfu
